### PR TITLE
new user auth flow (code review)

### PR DESCRIPTION
**Pull request by WesternConcrete**

### CODE REVIEW

**Comment by WesternConcrete** [comment]
This PR does 3 main things.

1. It completely gets rid of material UI
2. It adds a user authentication flow using Google and Next-Auth
3. It restyles all of our components using a mixture of tailwind css and shadcn-ui

**Comment by probably-neb** [comment]
I really like the enroll button idea, hopefully I'll have the sections scraping done in time so it's useful.
Overall great ui overhaul
LGTM!

**Comment by jchu37** [comment]
LGTM!

**Comment by WesternConcrete** [comment]
> sections

Sounds good! I think the auth page is done for the most part except it still need it to fix a few lint errors and redirect the user to auth if they arent logged in.

**Pull request merged**
